name = "hackage-index-state"
main = "src/index.ts"
compatibility_date = "2023-01-30"

kv_namespaces = [
  { binding = "trailers", id = "c0ea4578e6c542e19f214cad5b5beaa7", preview_id = "c2f363e4b9c6452a955dfe4208e76e4d" }
]
